# Generated by Django 4.1.7 on 2023-03-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_id_linkedin',
            field=models.TextField(blank=True, db_column='company_id_linkedin', default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_linkedin_url',
            field=models.TextField(blank=True, db_column='company_linkedin_url', default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.TextField(blank=True, db_column='industry', default=None, max_length=512, null=True),
        ),
    ]
