# Generated by Django 4.1.7 on 2023-03-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0004_remove_job_branch_id_job_company_id_delete_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='hardskillability',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='hardskillability',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='hardskillability',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='recruiter_id',
            new_name='recruiter',
        ),
        migrations.RenameField(
            model_name='languageability',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='languageability',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='languageability',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='softskillability',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='softskillability',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='softskillability',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
