# Generated by Django 4.1.7 on 2023-03-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0005_rename_job_id_application_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='list_my_jobs',
            field=models.BooleanField(db_column='list_my_jobs', default=True),
        ),
    ]
