# Generated by Django 4.1.7 on 2023-03-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0006_company_list_my_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.TextField(choices=[('Employee', 'Employee'), ('Project', 'Project'), ('Outsource', 'Outsource'), ('Internship', 'Intern')], db_column='employment_type', default='Employee'),
        ),
    ]
