# Generated by Django 4.1.7 on 2023-03-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0008_job_application_url_job_location_job_posted_on_epoch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted_on_epoch',
            field=models.BigIntegerField(blank=True, db_column='posted_on_epoch', null=True),
        ),
    ]
