# Generated by Django 4.1.7 on 2023-04-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0011_company_user_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_level',
            field=models.TextField(blank=True, db_column='job_level', max_length=128, null=True),
        ),
    ]
