# Generated by Django 4.1.7 on 2023-04-08 10:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs_app', '0012_job_job_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(blank=True, db_column='action_date', default=datetime.datetime.now)),
                ('status', models.BooleanField(blank=True, db_column='status', null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='jobs_app.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
