# Generated by Django 4.1.7 on 2023-04-09 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs_app', '0014_alter_favoritejobs_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='recruiter',
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
