# Generated by Django 4.1.7 on 2023-04-11 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs_app', '0016_remove_job_recruiter_job_recruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritejobs',
            name='status',
        ),
        migrations.AddField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(related_name='jobs_applied', through='jobs_app.Application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='favorited_by_user',
            field=models.ManyToManyField(related_name='jobs_favorites', through='jobs_app.FavoriteJobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobs_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
