# Generated by Django 4.1.7 on 2023-04-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0017_remove_favoritejobs_status_job_applicants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.TextField(blank=True, choices=[('Applied', 'Applied'), ('Approached', 'Approached'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled'), ('Contract', 'Contract'), ('Hired', 'Hired')], db_column='status', null=True),
        ),
    ]
