# Generated by Django 4.1.7 on 2023-04-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0018_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_deleted',
            field=models.BooleanField(db_column='is_deleted', default=False),
        ),
    ]
