# Generated by Django 4.1.7 on 2023-04-12 07:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0019_application_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status_updated',
        ),
        migrations.CreateModel(
            name='ApplicationFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, choices=[('Applied', 'Applied'), ('Approached', 'Approached'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled'), ('Contract', 'Contract'), ('Hired', 'Hired')], db_column='status', null=True)),
                ('status_updated', models.DateTimeField(blank=True, db_column='status_updated', default=datetime.datetime.now)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('to_do_date', models.DateTimeField(blank=True, db_column='to_do_date', default=datetime.datetime.now)),
                ('to_do', models.TextField(blank=True, db_column='to_do', max_length=1024, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='jobs_app.application')),
            ],
            options={
                'db_table': 'application_flow',
            },
        ),
    ]
