# Generated by Django 4.1.7 on 2023-04-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0020_remove_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationflow',
            name='is_deleted',
            field=models.BooleanField(db_column='is_deleted', default=False),
        ),
        migrations.AlterField(
            model_name='applicationflow',
            name='to_do_date',
            field=models.DateTimeField(blank=True, db_column='to_do_date', null=True),
        ),
    ]
